# Generated by Django 2.1.1 on 2018-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_more_text', models.CharField(max_length=1000)),
                ('contact_info', models.CharField(max_length=17)),
                ('first_heading', models.CharField(max_length=1000)),
                ('down_text', models.CharField(max_length=100)),
                ('first_screen_heading', models.CharField(max_length=1000)),
                ('second_screen_heading', models.CharField(max_length=1000)),
                ('second_screen_descr', models.CharField(max_length=1000)),
                ('third_screen_heading', models.CharField(max_length=1000)),
                ('third_screen_descr', models.CharField(max_length=1000)),
                ('fourth_screen_heading', models.CharField(max_length=1000)),
                ('fourth_screen_descr', models.CharField(max_length=1000)),
                ('fifth_screen_heading', models.CharField(max_length=1000)),
                ('fifth_screen_descr', models.CharField(max_length=1000)),
                ('sixth_screen_heading', models.CharField(max_length=1000)),
                ('seventh_screen_form_heading', models.CharField(max_length=1000)),
                ('seventh_screen_form_button_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
