# Generated by Django 2.1.1 on 2018-10-01 19:00

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_main', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('design', 'Дизайн'), ('house', 'Ремонт квартир и домов'), ('office', 'Ремонт офисов'), ('construction', 'Строительство домов')], max_length=80)),
                ('main_img', models.ImageField(blank=True, upload_to='admin/services')),
                ('top_left', models.CharField(max_length=500)),
                ('top_right', models.CharField(max_length=500)),
                ('bottom_left', models.CharField(max_length=500)),
                ('bottom_right', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(blank=True, upload_to='admin/services')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CatalogItem')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, verbose_name='Название компании')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('addr', models.CharField(max_length=500, verbose_name='Адрес')),
                ('working_time', models.CharField(max_length=500, verbose_name='Часы работы')),
                ('instagram_text', models.CharField(max_length=500, verbose_name='Текст instagram')),
                ('instagram_link', models.URLField(max_length=500, verbose_name='Ссылка на аккаунт в instagram')),
                ('development', models.CharField(max_length=500, verbose_name='Компания разработчик')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
            bases=(main.models.SingleInstanceOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title страницы')),
                ('heading', models.TextField(verbose_name='Заголовок на первом экране')),
                ('company_name_heading', models.TextField(verbose_name='Заголовок названия компании')),
                ('addr_heading', models.TextField(verbose_name='Заголовок адреса')),
                ('phone_heading', models.TextField(verbose_name='Заголовок телефона')),
                ('working_time_heading', models.TextField(verbose_name='Заголовок время работы')),
                ('email_heading', models.TextField(verbose_name='Заголовок email')),
                ('form_heading', models.TextField(verbose_name='Заголовок над формой')),
                ('submit_text', models.TextField(verbose_name='Текст в кнопке формы')),
            ],
            options={
                'verbose_name': 'Страница контакты',
                'verbose_name_plural': 'Страница контакты',
            },
            bases=(main.models.SingleInstanceOnly, models.Model),
        ),
        migrations.CreateModel(
            name='HeadingAndText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=300)),
                ('text', models.TextField(max_length=5000)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingAndTextImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='admin/misc')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.HeadingAndText')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_more_text', models.CharField(max_length=1000, verbose_name='Текст для кнопки узнать больше')),
                ('first_heading', models.CharField(max_length=1000, verbose_name='Заголовок на главной странице')),
                ('first_image', models.ImageField(blank=True, upload_to='admin/index', verbose_name='Картинка, отображающаяся на главной странице')),
                ('down_text', models.CharField(max_length=100, verbose_name='Текст "Вниз"')),
                ('second_screen_heading', models.TextField(max_length=1000, verbose_name='Заголовок второго экрана')),
                ('second_screen_image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка второго экрана')),
                ('second_screen_descr', models.TextField(max_length=1000, verbose_name='Описание второго экрана')),
                ('third_screen_heading', models.TextField(max_length=1000, verbose_name='Заголовок третьего экрана')),
                ('third_screen_image', models.ImageField(blank=True, upload_to='admin/index', verbose_name='Картинка третьего экрана')),
                ('third_screen_descr', models.TextField(max_length=1000, verbose_name='Описание третьего экрана')),
                ('fourth_screen_heading', models.TextField(max_length=1000, verbose_name='Заголовок четвертого экрана')),
                ('fourth_screen_image', models.ImageField(blank=True, upload_to='admin/index', verbose_name='Картинка четвертого экрана')),
                ('fourth_screen_descr', models.TextField(max_length=1000, verbose_name='Описание четвертого экрана')),
                ('fifth_screen_heading', models.TextField(max_length=1000, verbose_name='Заголовок пятого экрана')),
                ('fifth_screen_image', models.ImageField(blank=True, upload_to='admin/index', verbose_name='Картинка пятого экрана')),
                ('fifth_screen_descr', models.TextField(max_length=1000, verbose_name='Описание пятого экрана')),
                ('sixth_screen_heading', models.TextField(max_length=1000, verbose_name='Заголовок шестого экрана')),
                ('seventh_screen_form_heading', models.CharField(max_length=1000, verbose_name='Заголовок формы')),
                ('seventh_screen_form_button_text', models.CharField(max_length=1000, verbose_name='Текст в кнопке отправить')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
            bases=(main.models.SingleInstanceOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_page_title', models.CharField(max_length=200)),
                ('single_item_top_left_heading', models.CharField(max_length=500)),
                ('single_item_top_right_heading', models.CharField(max_length=500)),
                ('single_item_bottom_left_heading', models.CharField(max_length=500)),
                ('single_item_bottom_right_heading', models.CharField(max_length=500)),
            ],
            bases=(main.models.SingleInstanceOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceItemAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[['design', 'Дизайн'], ['house repair', 'Ремонт квартир и домов'], ['office repair', 'Ремонт офисов'], ['construction', 'Строительство домов']], max_length=150)),
                ('name', models.TextField(max_length=500)),
                ('preview_img', models.ImageField(blank=True, upload_to='admin/index/services')),
                ('main_img', models.ImageField(blank=True, upload_to='admin/index/services')),
                ('image_text', models.TextField(max_length=500)),
                ('accordion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ServiceItemAccordion')),
                ('headings_with_text_blocks', models.ManyToManyField(blank=True, to='main.HeadingAndText')),
                ('projects', models.ManyToManyField(blank=True, to='main.CatalogItem')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('heading', models.TextField(max_length=500)),
                ('text_block_left', models.TextField(max_length=1500)),
                ('text_block_right', models.TextField(max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.ProjectsPage'),
        ),
    ]
