# Generated by Django 2.1.1 on 2018-09-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='first_screen_heading',
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='contact_info',
            field=models.CharField(max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='down_text',
            field=models.CharField(max_length=100, verbose_name='Текст "Вниз"'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fifth_screen_descr',
            field=models.CharField(max_length=1000, verbose_name='Описание пятого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fifth_screen_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок пятого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='first_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок на главной странице'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fourth_screen_descr',
            field=models.CharField(max_length=1000, verbose_name='Описание четвертого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fourth_screen_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок четвертого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='learn_more_text',
            field=models.CharField(max_length=1000, verbose_name='Текст для кнопки узнать больше'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_screen_descr',
            field=models.CharField(max_length=1000, verbose_name='Описание второго экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_screen_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок второго экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='seventh_screen_form_button_text',
            field=models.CharField(max_length=1000, verbose_name='Текст в кнопке отправить'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='seventh_screen_form_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='sixth_screen_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок шестого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='third_screen_descr',
            field=models.CharField(max_length=1000, verbose_name='Описание третьего экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='third_screen_heading',
            field=models.CharField(max_length=1000, verbose_name='Заголовок третьего экрана'),
        ),
    ]
