# Generated by Django 2.1.1 on 2018-09-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180923_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSingleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='id',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='basesingleton_ptr',
            field=models.OneToOneField(auto_created=True, default=10, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseSingleton'),
            preserve_default=False,
        ),
    ]
