# Generated by Django 2.1.1 on 2018-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180923_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='basesingleton_ptr',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BaseSingleton',
        ),
    ]
