# Generated by Django 2.1.1 on 2018-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180923_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fifth_screen_descr',
            field=models.TextField(max_length=1000, verbose_name='Описание пятого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fifth_screen_heading',
            field=models.TextField(max_length=1000, verbose_name='Заголовок пятого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fourth_screen_descr',
            field=models.TextField(max_length=1000, verbose_name='Описание четвертого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='fourth_screen_heading',
            field=models.TextField(max_length=1000, verbose_name='Заголовок четвертого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_screen_descr',
            field=models.TextField(max_length=1000, verbose_name='Описание второго экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_screen_heading',
            field=models.TextField(max_length=1000, verbose_name='Заголовок второго экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='sixth_screen_heading',
            field=models.TextField(max_length=1000, verbose_name='Заголовок шестого экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='third_screen_descr',
            field=models.TextField(max_length=1000, verbose_name='Описание третьего экрана'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='third_screen_heading',
            field=models.TextField(max_length=1000, verbose_name='Заголовок третьего экрана'),
        ),
    ]
