# Generated by Django 2.1.1 on 2018-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180924_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='addr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='development',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
