# Generated by Django 2.1.1 on 2018-09-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_catalogitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='top_left',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='type',
            field=models.CharField(choices=[('design', 'Дизайн'), ('house', 'Ремонт квартир и домов'), ('office', 'Ремонт офисов'), ('construction', 'Строительство домов')], max_length=80),
        ),
    ]
