# Generated by Django 2.1.1 on 2018-09-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0011_auto_20180924_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingAndText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=300)),
                ('text', models.TextField(max_length=5000)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_page_title', models.CharField(max_length=200)),
                ('single_item_top_left_heading', models.CharField(max_length=500)),
                ('single_item_top_right_heading', models.CharField(max_length=500)),
                ('single_item_bottom_left_heading', models.CharField(max_length=500)),
                ('single_item_bottom_right_heading', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='servicespage',
            old_name='single_item_bottom_left_heading',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='services_page_title',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='single_item_bottom_right_heading',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='single_item_top_left_heading',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='single_item_top_right_heading',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='heading',
            field=models.TextField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_block_left',
            field=models.TextField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_block_right',
            field=models.TextField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.ProjectsPage'),
        ),
    ]
