# Generated by Django 2.1.1 on 2018-09-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180928_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[['design', 'Дизайн'], ['house repair', 'Ремонт квартир и домов'], ['office repair', 'Ремонт офисов'], ['construction', 'Строительство домов']], max_length=150)),
                ('name', models.TextField(max_length=500)),
                ('preview_img', models.ImageField(blank=True, upload_to='admin/index/services')),
                ('main_img', models.ImageField(blank=True, upload_to='admin/index/services')),
                ('image_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='serviceitemaccordion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ServicesItem'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='to_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ServicesItem'),
        ),
    ]
