# Generated by Django 2.1.1 on 2018-09-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180929_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='to_service',
        ),
        migrations.AddField(
            model_name='servicesitem',
            name='catalog_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.CatalogItem'),
        ),
    ]
