# Generated by Django 2.1.1 on 2018-09-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180929_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesitem',
            name='catalog_items',
        ),
    ]
