# Generated by Django 2.1.1 on 2018-09-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_servicesitem_catalog_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='to_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ServicesItem'),
        ),
    ]
