# Generated by Django 2.1.1 on 2018-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_servicesitem_accordions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesitem',
            name='accordions',
        ),
        migrations.AddField(
            model_name='servicesitem',
            name='accordions',
            field=models.ManyToManyField(blank=True, to='main.ServiceItemAccordion'),
        ),
    ]
