# Generated by Django 2.1.1 on 2018-09-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180930_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitemaccordion',
            name='service',
        ),
    ]
