# Generated by Django 2.1.1 on 2018-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180930_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='to_service',
        ),
        migrations.AddField(
            model_name='servicesitem',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.CatalogItem'),
        ),
    ]
