# Generated by Django 2.1.1 on 2018-09-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180930_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesitem',
            name='headings_with_text_blocks',
            field=models.ManyToManyField(blank=True, to='main.HeadingAndText'),
        ),
    ]
