# Generated by Django 2.1.1 on 2018-09-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_servicesitem_headings_with_text_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesitem',
            old_name='accordions',
            new_name='accordion',
        ),
    ]
