# Generated by Django 2.1.1 on 2018-09-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180930_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingAndTextImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='admin/misc')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeadingAndText')),
            ],
        ),
    ]
