# Generated by Django 2.1.1 on 2018-10-01 18:47

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_headingandtextimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title страницы')),
                ('heading', models.TextField(verbose_name='Заголовок на первом экране')),
                ('first_heading', models.TextField(verbose_name='Заголовок названия компании')),
                ('second_heading', models.TextField(verbose_name='Заголовок адреса')),
                ('third_heading', models.TextField(verbose_name='Заголовок телефона')),
                ('fourth_heading', models.TextField(verbose_name='Заголовок время работы')),
                ('fifth_heading', models.TextField(verbose_name='Заголовок email')),
                ('form_heading', models.TextField(verbose_name='Заголовок над формой')),
            ],
            options={
                'verbose_name': 'Страница контакты',
                'verbose_name_plural': 'Страница контакты',
            },
            bases=(main.models.SingleInstansOnlyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_time',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headingandtextimage',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.HeadingAndText'),
        ),
    ]
