# Generated by Django 2.1.1 on 2018-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20181001_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='company_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
