# Generated by Django 2.1.1 on 2018-10-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contactinfo_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactspage',
            old_name='second_heading',
            new_name='addr_heading',
        ),
        migrations.RenameField(
            model_name='contactspage',
            old_name='first_heading',
            new_name='company_name_heading',
        ),
        migrations.RenameField(
            model_name='contactspage',
            old_name='fifth_heading',
            new_name='email_heading',
        ),
        migrations.RenameField(
            model_name='contactspage',
            old_name='third_heading',
            new_name='phone_heading',
        ),
        migrations.RenameField(
            model_name='contactspage',
            old_name='fourth_heading',
            new_name='working_time_heading',
        ),
    ]
