# Generated by Django 2.1.1 on 2018-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20181001_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='submit_text',
            field=models.TextField(default='', verbose_name='Текст в кнопке формы'),
            preserve_default=False,
        ),
    ]
